const actionTypes = {
  ADD_HOTBAR: 'ADD_HOTBAR',
  ADD_ITEM: 'ADD_ITEM',
  CAPTURE_MEMORY: 'CAPTURE_MEMORY',
  DESTROY_ITEM: 'DESTROY_ITEM',
  INITIALIZE_GAME_STATE: 'INITIALIZE_GAME_STATE',
  LOAD_GAME_STATE: 'LOAD_GAME_STATE',
  MOVE_ITEMS: 'MOVE_ITEMS',
  SAVE_GAME_STATE: 'SAVE_GAME_STATE',
  UPDATE_DEBUG_STATE: 'UPDATE_DEBUG_STATE',
}





export default actionTypes
