const actionTypes = {
  ADD_HOTBAR: 'ADD_HOTBAR',
  ADD_ITEM: 'ADD_ITEM',
  ADD_MEMORY: 'ADD_MEMORY',
  DESTROY_ITEM: 'DESTROY_ITEM',
  INITIALIZE_GAME_STATE: 'INITIALIZE_GAME_STATE',
  LOAD_GAME_STATE: 'LOAD_GAME_STATE',
  LOAD_MEMORIES: 'LOAD_MEMORIES',
  MOVE_ITEMS: 'MOVE_ITEMS',
  SAVE_GAME_STATE: 'SAVE_GAME_STATE',
  SET_CONTROL_STATE: 'SET_CONTROL_STATE',
  START_MEMORY_CAPTURE: 'START_MEMORY_CAPTURE',
  STOP_MEMORY_CAPTURE: 'STOP_MEMORY_CAPTURE',
  UNSET_PRESS_CONTROLS: 'UNSET_PRESS_CONTROLS',
  UPDATE_DEBUG_STATE: 'UPDATE_DEBUG_STATE',
}





export default actionTypes
